### PR TITLE
Add preferred app locale settings

### PR DESCRIPTION
**Pull request by nohli**
`openAppLocaleSettings` is a copy of `openAppSettings` with a different `Intent`.
Maybe there can be a method for both, with a parameter.

### CODE REVIEW

**Comment by spencerccf** [comment]
@nohli  Could you please update change log and minor version when you get a chance and I will get merged into master.

**Comment by nohli** [comment]
@spencerccf you merged and then reverted the changes.

Do you still want me to update change log and minor version (and open a new PR)?

**Comment by plinkos** [comment]
Yes please

**Comment by nohli** [comment]
https://github.com/spencerccf/app_settings/pull/183

**Pull request merged**
