### PR TITLE
Add support to Flutter <= 3.0.1

### PR DESCRIPTION
**Pull request by matAlmeida**
## Changes

- Add supported flutter version `<= 3.0.1`

## Evidence

Example app running on flutter 3.0.1

image

### CODE REVIEW

**Comment by matAlmeida** [comment]
Found a bug

**Comment by Galti** [comment]
@plinkos is there a problem with the PR? I see it isn't merged yet.

**Comment by plinkos** [comment]
Sorry for the delay

**Comment by plinkos** [comment]
Done... should be updating out on pub.dev right now.

**Comment by Galti** [comment]
Great! Thanks.

**Pull request merged**
