### PR TITLE
Add possibility to open settings activity as another task

### PR DESCRIPTION
**Pull request by mat-sienczyk**

### CODE REVIEW

**Comment by plinkos** [comment]
I’ll get this merged in today and push up a new version to pub Dev 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mat-sienczyk** [comment]
Didn't test this on iOS, but 99,99% should work as before.

**Comment by plinkos** [comment]
No prob, I can test on iOS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alectogeek** [comment]
Please, add `asAnotherTask` desctiption to the documentation

**Comment by Shahmirzali-Huseynov** [comment]
Please, add `asAnotherTask` desctiption to the documentation

**Pull request merged**
