### PR TITLE
Ports the Android Plugin component back to Java

### PR DESCRIPTION
**Pull request by ened**
... which reduces overall app size and compile times.

This PR also changes a few other things:
 - Upgrade grade plugin & sets used Android SDK version to 28
 - Simplifies the example by removing the geolocator dependency (not used or required to showcase the plugin)
 - Add the missing "Open App Settings" button to example
 - Replaces Future with Future<void> as the calls do not return any value (probably need to add a `await`).

@spencerccf WDYT? Would you like the PR to be split up if necessary?

### CODE REVIEW

**Comment by spencerccf** [comment]
Hi @ened,

Yes, could you split the PR so that the rollback to Java changes are separate from your other updates?

**Comment by ened** [comment]
@spencerccf this has been done - please check again.

**Comment by ened** [comment]
@spencerccf hi - any update, please?

**Comment by spencerccf** [comment]
@ened I generated a new repo from your Java branch: https://github.com/spencerccf/app_settings_je  I would like to publish a separate https://pub.dev plugin so that we can support both Kotlin and Java.  Please give this a review and let me know your thoughts.

**Comment by ened** [comment]
@spencerccf The java PR is meant as a _replacement_ for the Kotlin port, as it significantly reduces external dependencies (on the Kotlin SDK, the build system etc) which improves the developer experience for users of this plugin.

Kotlin & Java are compatible with each other, therefore you don't need to create a separate repo or pub.

**Comment by ened** [comment]
@spencerccf how are you doing? Should we continue on this PR?

**Comment by plinkos** [comment]
I think moving from Kotlin back to Java would be a fallback as Google has announced Kotlin as the official language of Android moving forward.  I’m happy to support a separate plugin for Java but I think having a Kotilin plugin moving forward is very important. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
